#!/usr/bin/env bash

todo_dir="$HOME/doix/"
todo_file="$todo_dir/doix.md"
backlog_file="$todo_dir/backlog.md"
done_file="$todo_dir/done.md"

cmd=$1
shift

highlight_text () {
  printf "\x1b[31m%s\x1b[0m\n" "$1"
}

run_init() {
  if [[ -d "$todo_dir" ]]; then
    echo "doix directory already exists"
  else
    mkdir -p $todo_dir
    touch $done_file
    touch $backlog_file
    printf "%b" \
    "# Doix\n\n---\n\nactive_context:\n"\
    "active_project:\n"\
    "last_modified: 2026-02-11\n\n---\n\n"\
    "## Active Tasks\n\n## Captured Tasks\n\n"\
    "## Events\n\n## Weekly Recurring\n\n"\
    "## Monthly Recurring\n" > "$todo_file"
    echo "initialized doix directory at $todo_dir"
  fi
}

run_add() {
  local task_desc="$*"
  sed -i "/^## Captured Tasks$/a $task_desc" $todo_file
}

run_list() {
  local seach_term="$*"

  filter_recurring () {
    rg -v -- '^\s*-\s*\[x\]\s'
  }

  filter_events() {
    awk '
      BEGIN {
        now = systime()
        end = now + 30*24*60*60
      }
      function to_epoch(d) {
        split(d, a, "-")
        return mktime(a[1]" "a[2]" "a[3]" 00 00 00")
      }
      {
        date = $1
        if (date ~ /^[0-9]{4}-[0-9]{2}-[0-9]{2}$/) {
          t = to_epoch(date)
          if (t >= now && t <= end)
            print
        }
      }
    '
  }

  print_section () {
    local title=$1
    local content=$(awk "/^## $title/{flag=1; next} /^## /{flag=0} flag" $todo_file)

    case "$title" in
      "Weekly Recurring"|"Monthly Recurring")
        content=$(echo "$content" | filter_recurring)
        ;;
      "Events")
        content=$(echo "$content" | filter_events)
        ;;
    esac

    if [[ -n $seach_term ]]; then
      content=$(echo "$content" | rg --color=always -- "$seach_term")
    fi 

    if [[ -n $content ]]; then
      highlight_text "$title"
      printf "%s\n\n" "$content"
    # else
    #   echo "none"
    fi
  }
  print_section "Active Tasks"
  print_section "Captured Tasks"
  print_section "Events"
  print_section "Weekly Recurring"
  print_section "Monthly Recurring"
}

run_remove() {
  local substring="$*"
  local match=$(grep -n -- "$substring" "$todo_file" | head -n1)
  local line=$(echo "$match" | cut -d: -f1)

  if [[ -z $match ]]; then
    printf "No task found matching: %s\n" "$substring"
    return 1
  fi

  echo "$match"
  read -p "Delete task? [y/n] " ans
  if [[ $ans =~ ^[Yy]$ ]]; then
    sed -i "${line}d" "$todo_file"
  else
    echo "Cancelled by the user"
  fi
}

run_edit() {
  local substring="$*"
  local match=$(grep -n -- "$substring" "$todo_file" | head -n1)
  local line=$(echo "$match" | cut -d: -f1)

  if [[ -z $match ]]; then
    printf "No task found matching: %s\n" "$substring"
    return 1
  fi

  echo "$match"
  read -p "Edited task: " new_task
  sed -i "${line}s/.*/$new_task/" "$todo_file"
}

run_backlog() {
  local seach_term="$*"
  local content=$(cat $backlog_file)

  if [[ -n $seach_term ]]; then
    content=$(echo "$content" | rg --color=always -- "$seach_term")
  fi 

  if [[ -n $content ]]; then
    highlight_text "Backlog"
    printf "%s\n\n" "$content"
  else
    echo "none"
  fi
}

run_done() {
  local substring="$*"
  local match=$(grep -n -- "$substring" "$todo_file" | head -n1)
  local line=$(echo "$match" | cut -d: -f1)
  local text=$(echo "$match" | cut -d: -f2)

  if [[ -z $match ]]; then
    printf "No task found matching: %s\n" "$substring"
    return 1
  fi

  echo "$match"
  read -p "complete task? [y/n] " ans
  if [[ $ans =~ ^[Yy]$ ]]; then
    printf "x $(date +%F) %s\n" "$text" >> $done_file
    sed -i "${line}d" "$todo_file"
  else
    echo "Cancelled by the user"
  fi
}

run_default() {
    local cyan=$(tput setaf 67)      # Muted blue
    local blue=$(tput setaf 109)     # Frost blue
    local green=$(tput setaf 108)    # Aurora green
    local yellow=$(tput setaf 179)   # Warm gray
    local magenta=$(tput setaf 139)  # Purple gray
    local red=$(tput setaf 174)      # Muted red
    local gray=$(tput setaf 242)
    local reset=$(tput sgr0)
    
    cat << EOF
${cyan}     ┌─────┐   ▄${reset}
${cyan}     │    ▄│   █      ▄         ${gray}│${reset}  ${yellow}Reimplementation of todo.txt in${reset}
${cyan}     │▄ ▄▀ │ ▄▄█  ▄▄▄ ▄ ▄ ▄${reset}     ${gray}│${reset}  ${yellow}markdown with a litte gtd candy${reset}
${cyan}     │ ▀   │${blue}█░░█ █░░█ █ ▐▒▌${reset}     ${gray}│${reset}
${cyan}     └─────┘${reset} ${blue}▀▀▀  ▀▀  ▀ ▀ ▀${reset}     ${gray}│${reset}
${blue}   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒${reset}   ${gray}│${reset}
${green}   ░░░░░░░░░░░░░░░░░░░░░░░░░░${reset}   ${gray}│${reset}
                                ${gray}│${reset}  ${magenta}made by eduardofuncao${reset}


   ${green}\$ doix help${reset}              ${gray}getting started${reset}
   ${green}\$ doix help <command>${reset}    ${gray}command specific instructions${reset}


EOF
}

case "$cmd" in
  "init"|"start") run_init
  ;;
  "add"|"a") run_add $@
  ;;
  "list"|"ls") run_list $@
  ;;
  "remove"|"rm") run_remove $@
  ;;
  "edit"|"ed") run_edit $@
  ;;
  "backlog"|"log") run_backlog $@
  ;;
  "done") run_done $@
  ;;
  *) run_default
  ;;
esac
