#!/usr/bin/env bash

todo_dir="$HOME/doix/"
todo_file="$todo_dir/doix.md"
backlog_file="$todo_dir/backlog.md"
done_file="$todo_dir/done.md"

cmd=$1
shift

highlight_text () {
  printf "\x1b[31m%s\x1b[0m\n" "$*"
}

fade_text () {
  printf "\x1b[2m%s\x1b[0m\n" "$*"
}

run_init() {
  if [[ -d "$todo_dir" ]]; then
    echo "doix directory already exists"
  else
    mkdir -p $todo_dir
    touch $done_file
    printf "%b" "# Backlog\n\n## Captured Tasks" > "$backlog_file"
    printf "%b" \
    "# Doix\n\n---\n\nactive_context:\n"\
    "active_project:\n"\
    "last_modified: 2026-02-11\n\n---\n\n"\
    "## Active Tasks\n\n## Captured Tasks\n\n"\
    "## Events\n\n## Weekly Recurring\n\n"\
    "## Monthly Recurring\n" > "$todo_file"
    echo "initialized doix directory at $todo_dir"
  fi
}

run_add() {
  local task_desc="$*"
  sed -i "/^## Captured Tasks$/a $context $task_desc" $backlog_file
}

run_list() {
  local seach_term="$*"

  filter_recurring () {
    rg -v -- '^\s*-\s*\[x\]\s'
  }

  filter_events() {
    awk '
      BEGIN {
        now = systime()
        end = now + 30*24*60*60
      }
      function to_epoch(d) {
        split(d, a, "-")
        return mktime(a[1]" "a[2]" "a[3]" 00 00 00")
      }
      {
        date = $1
        if (date ~ /^[0-9]{4}-[0-9]{2}-[0-9]{2}$/) {
          t = to_epoch(date)
          if (t >= now && t <= end)
            print
        }
      }
    '
  }

  print_section () {
    local title=$1
    local file=$2
    local content=$(awk "/^## $title/{flag=1; next} /^## /{flag=0} flag" $file)

    case "$title" in
      "Weekly Recurring"|"Monthly Recurring")
        content=$(echo "$content" | filter_recurring)
        ;;
      "Events")
        content=$(echo "$content" | filter_events)
        ;;
    esac


    if [[ -n $context ]]; then
      content=$(echo "$content" | rg --color=always -- "$context")
    fi

    if [[ -n $seach_term ]]; then
      content=$(echo "$content" | rg --color=always -- "$seach_term")
    fi 

    if [[ -n $content ]]; then
      highlight_text "$title"
      printf "%s\n\n" "$content"
    # else
    #   echo "none"
    fi
  }

  if [[ -n $context ]]; then
    echo  "$(fade_text "context: "$context)"
  fi

  print_section "Active Tasks" $todo_file
  print_section "Captured Tasks" $backlog_file
  print_section "Events" $todo_file
  print_section "Weekly Recurring" $todo_file
  print_section "Monthly Recurring" $todo_file
}

run_remove() {
  local substring="$*"
  local match=$(grep -n -- "$substring" "$todo_file" "$backlog_file" | head -n1)
  
  if [[ -z $match ]]; then
    printf "No task found matching: %s\n" "$substring"
    return 1
  fi
  
  local file=$(echo "$match" | cut -d: -f1)
  local line=$(echo "$match" | cut -d: -f2)
  local text=$(echo "$match" | cut -d: -f3-)
  
  echo "$line:$text"
  echo "$(fade_text "File: $(basename "$file")")"
  read -p "Delete task? [y/n] " ans
  
  if [[ $ans =~ ^[Yy]$ ]]; then
    sed -i "${line}d" "$file"
    echo "Deleted from $(basename "$file")"
  else
    echo "Cancelled by the user"
  fi
}

run_edit() {
  local substring="$*"
  local match=$(grep -n -- "$substring" "$todo_file" | head -n1)
  local line=$(echo "$match" | cut -d: -f1)

  if [[ -z $match ]]; then
    printf "No task found matching: %s\n" "$substring"
    return 1
  fi

  echo "$match"
  read -p "Edited task: " new_task
  sed -i "${line}s/.*/$new_task/" "$todo_file"
}

run_backlog() {
  local seach_term="$*"
  local content=$(cat $backlog_file)

  if [[ -n $seach_term ]]; then
    content=$(echo "$content" | rg --color=always -- "$seach_term")
  fi 

  if [[ -n $content ]]; then
    highlight_text "Backlog"
    printf "%s\n\n" "$content"
  else
    echo "none"
  fi
}

run_activate() {
  echo "not implemented yet :("
}

run_context() {
  new_context="$*"

  if [[ -z $new_context ]]; then
    if [[ -z $context ]];then
      echo "context not set, use doix ctx <context>"
    else
      echo "context set to $(highlight_text $context)"
    fi
    return 0
  fi

  if [[ $new_context == "none" ]]; then
    sed -i "s/^active_context:.*/active_context:/" "$todo_file"
    echo "context unset"
    return 0
  fi

  sed -i "s/^active_context:.*/active_context: $new_context/" "$todo_file"
  echo "context set to $(highlight_text $new_context)"
}

run_done() {
  local substring="$*"
  local match=$(grep -n -- "$substring" "$todo_file" | head -n1)
  local line=$(echo "$match" | cut -d: -f1)
  local text=$(echo "$match" | cut -d: -f2)

  if [[ -z $match ]]; then
    printf "No task found matching: %s\n" "$substring"
    return 1
  fi

  echo "$match"
  read -p "complete task? [y/n] " ans
  if [[ $ans =~ ^[Yy]$ ]]; then
    printf "x $(date +%F) %s\n" "$text" >> $done_file
    sed -i "${line}d" "$todo_file"
  else
    echo "Cancelled by the user"
  fi
}

run_default() {
    local cyan=$(tput setaf 67)
    local blue=$(tput setaf 109)
    local green=$(tput setaf 108)
    local yellow=$(tput setaf 179)
    local magenta=$(tput setaf 139)
    local red=$(tput setaf 174)
    local gray=$(tput setaf 242)
    local reset=$(tput sgr0)
    
    cat << EOF
${cyan}     ┌─────┐   ▄${reset}
${cyan}     │    ▄│   █      ▄         ${gray}│${reset}  ${yellow}Reimplementation of todo.txt in${reset}
${cyan}     │▄ ▄▀ │ ▄▄█  ▄▄▄ ▄ ▄ ▄${reset}     ${gray}│${reset}  ${yellow}markdown with a litte gtd candy${reset}
${cyan}     │ ▀   │${blue}█░░█ █░░█ █ ▐▒▌${reset}     ${gray}│${reset}
${cyan}     └─────┘${reset} ${blue}▀▀▀  ▀▀  ▀ ▀ ▀${reset}     ${gray}│${reset}
${blue}   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒${reset}   ${gray}│${reset}
${green}   ░░░░░░░░░░░░░░░░░░░░░░░░░░${reset}   ${gray}│${reset}
                                ${gray}│${reset}  ${magenta}made by eduardofuncao${reset}


   ${magenta}Every task lives in doix.md, backlog.md, and done.md, in the \$HOME/doix/ directory ${reset}
   ${magenta}At the start of the week, move tasks from the backlog to the doix file${reset}
   ${magenta}finish all your active tasks by the end of the week to get things done${reset}

   ${green}\$ doix help <command>${reset}    ${gray}command specific instructions${reset}

   ${green}\$ doix add @house make the bed${reset}    ${gray}add task to captured tasks${reset}
   ${green}\$ doix ls @house${reset}    ${gray}list every tasks containing the substring '@house'${reset}
   ${green}\$ doix done bed${reset}    ${gray}move the first task containing 'bed' to the done file${reset}



EOF
}



context=$(grep "^active_context:" "$todo_file" | sed 's/^active_context: *//')

case "$cmd" in
  "init"|"start") run_init
  ;;
  "add"|"a") run_add $@
  ;;
  "list"|"ls") run_list $@
  ;;
  "remove"|"rm") run_remove $@
  ;;
  "edit"|"ed") run_edit $@
  ;;
  "backlog"|"log") run_backlog $@
  ;;
  "activate"|"start") run_activate $@
  ;;
  "context"|"ctx") run_context $@
  ;;
  "done") run_done $@
  ;;
  *) run_default
  ;;
esac
